/// Marks a protocol as an injectable dependency, generating an `InjectionKey`-conforming
/// key type for it.
///
/// The macro emits a peer declaration named `<Protocol>DependencyKey` whose static
/// `liveValue` returns a new instance of the concrete implementation. By default the
/// implementation is assumed to be `<Protocol>Impl`; use `implementationName` to
/// override.
///
/// The emitted key type inherits the access level of the annotated protocol
/// (`public` protocols produce `public` keys, `internal` protocols produce `internal` keys).
///
/// ```swift
/// @Injectable
/// public protocol FileUtility {
///     func fileExists(at: URL) -> Bool
/// }
/// ```
///
/// expands to:
///
/// ```swift
/// public struct FileUtilityDependencyKey: InjectionKey {
///     public static var liveValue: FileUtility { FileUtilityImpl() }
/// }
/// ```
///
/// - Parameter implementationName: The type name to instantiate inside `liveValue`.
///   Defaults to `<Protocol>Impl` when `nil`.
@attached(peer, names: suffixed(DependencyKey))
public macro Injectable(
    implementationName: String? = nil
) = #externalMacro(module: "SwiftyScriptyMacrosPlugin", type: "InjectableMacro")


/// Emits a computed property on `InjectedValues` that resolves the given type via its
/// macro-generated `<Type>DependencyKey`.
///
/// Intended to be used inside `extension InjectedValues { ... }`. This is what makes
/// `@Injected(\.foo)` KeyPaths compile at call sites. In this repo the surrounding
/// extension file is generated by Sourcery from every `@Injectable`-annotated protocol
/// in the module.
///
/// ```swift
/// extension InjectedValues {
///     #injected(FileUtility.self, accessLevel: "public")
///     #injected(Shell.self, accessLevel: "public")
/// }
/// ```
///
/// each call expands to:
///
/// ```swift
/// public var fileUtility: FileUtility {
///     get { return Self[FileUtilityDependencyKey.self] }
/// }
/// ```
///
/// The property name is derived by lowercasing the first word of the type name
/// (`URLSession` → `urlSession`, `MakeSwiftScript` → `makeSwiftScript`).
///
/// - Parameters:
///   - type: The protocol whose macro-generated key should be resolved.
///   - accessLevel: The Swift access modifier prefix (e.g. `"public"`) applied to the
///     emitted var. Defaults to `""` (module-internal).
@freestanding(declaration, names: arbitrary)
public macro injected<T>(
    _ type: T.Type,
    accessLevel: String = ""
) = #externalMacro(module: "SwiftyScriptyMacrosPlugin", type: "InjectedMacro")
